// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMenuData, GetMenuResponses, GetOrderingWindowData, GetOrderingWindowResponses, GetOrdersForTodayData, GetOrdersForTodayResponses, PlaceOrderData, PlaceOrderResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Gibt die aktuelle Speisekarte zurück.
 */
export const getMenu = <ThrowOnError extends boolean = false>(options?: Options<GetMenuData, ThrowOnError>) => (options?.client ?? client).get<GetMenuResponses, unknown, ThrowOnError>({ url: '/api/menu', ...options });

/**
 * Gibt das aktuelle Bestellfenster zurück (Tag, ob offen, Cutoff-Zeit).
 */
export const getOrderingWindow = <ThrowOnError extends boolean = false>(options?: Options<GetOrderingWindowData, ThrowOnError>) => (options?.client ?? client).get<GetOrderingWindowResponses, unknown, ThrowOnError>({ url: '/api/ordering-window', ...options });

/**
 * Listet alle Bestellungen des aktuellen Tages.
 */
export const getOrdersForToday = <ThrowOnError extends boolean = false>(options?: Options<GetOrdersForTodayData, ThrowOnError>) => (options?.client ?? client).get<GetOrdersForTodayResponses, unknown, ThrowOnError>({ url: '/api/orders/today', ...options });

/**
 * Erstellt eine neue Bestellung für den aktuellen Tag.
 */
export const placeOrder = <ThrowOnError extends boolean = false>(options: Options<PlaceOrderData, ThrowOnError>) => (options.client ?? client).post<PlaceOrderResponses, unknown, ThrowOnError>({
    url: '/api/orders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
