// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5252/' | (string & {});
};

export type AddResponse = {
    result: number | string;
};

export type AddData = {
    body?: never;
    path?: never;
    query: {
        left: number | string;
        right: number | string;
    };
    url: '/api/calculator/add';
};

export type AddResponses = {
    /**
     * OK
     */
    200: AddResponse;
};

export type AddResponse2 = AddResponses[keyof AddResponses];
